name: "Install Poetry Action"
author: "Sondre Lillebø Gundersen <sondrelg@live.no>"
description: "Installs and configures Poetry"
branding:
  icon: "package"
  color: "green"
inputs:
  version:
    description: "The Poetry version to install"
    required: true
    default: "1.1.6"
  virtualenvs-create:
    description: "Whether Poetry should create a virtualenv or not"
    required: false
    default: "true"
  virtualenvs-in-project:
    description: "Whether Poetry should create virtualenvs in the project directory or not"
    required: false
    default: "false"
  virtualenvs-path:
    description: "The Poetry virtualenv path"
    required: false
    default: "{cache-dir}/virtualenvs"
runs:
  using: "composite"
  steps:
    - name: Install and configure Poetry
      run: |
        installation_script="$(mktemp)"
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/48339106eb0d403a3c66519317488c8185844b32/install-poetry.py --output "$installation_script"

        config_script="$(mktemp)"
        curl -sSL https://raw.githubusercontent.com/snok/install-poetry/v1.2/scripts/v1.2/main.sh --output "$config_script"
        chmod +x "$config_script"

        $config_script \
          ${{ runner.os }} \
          ${{ inputs.virtualenvs-create }} \
          ${{ inputs.virtualenvs-in-project }} \
          ${{ inputs.virtualenvs-path }} \
          ${{ inputs.version }} \
          $installation_script
      shell: bash
